### ISSUE TITLE
Label is optional for even tracking

### ISSUE THREAD

**Issue by stiefdirckx** [JimBobSquarePants/jQuery-Google-Analytics#3]
According to the GA event tracking documentation 'Label' is an optional string.
https://developers.google.com/analytics/devguides/collection/gajs/eventTrackerGuide#Labels

So I presume it should be:

``` javascript
label: {
    value: null,
    validation: "optString",
    type: "string"
},
```

**Comment by JimBobSquarePants** [comment]
Thanks again. :) You're absolutely correct.

**Comment by stiefdirckx** [comment]
No worries. I'm going to use GA even tracking in a website I'm working on. And your script was the best I could find to make it as easy as possible.

I still have one problem though. If I want to use a numeric value for a parameter that is defined as a sting (like 'Label') the validation fails. But any non-null value should pass as a string I think.

Any idea what the best fix would be?

**Comment by JimBobSquarePants** [comment]
Sorry I didn't see this. I shall check it out.

**Comment by JimBobSquarePants** [comment]
I've fixed the validation bug and did some proper testing to fix another few things. It should work a lot better now.
