### ISSUE TITLE
Skipping optional paramater causes invalid tracking code

### ISSUE THREAD

**Issue by stiefdirckx** [JimBobSquarePants/jQuery-Google-Analytics#4]
When I want to skip the 'Label' or 'Value' parameter but still want to pass in the 'Non-interaction' parameter the tracking code is not valid.

This is what gets logged in debug mode:

```
Pushing Google analytics data. ["_trackEvent", "ABC", "DEF", "X10455", true]
```

But this should be:

```
Pushing Google analytics data. ["_trackEvent", "ABC", "DEF", "X10455", null, true]
```

This has got something to do with the .map method that automatically removes empty values. I think using the .each method could prevent this.

**Comment by stiefdirckx** [comment]
I made some changes to the function that gathers all the parameters but I'm not sure this is all correct in all situations.

I've added a 'params' array to which I add the parameter values. Null value items are also added to the array. At the end I remove null values at the back of the array but null values that are behind non-null values remain in the array. The array is then passed back. This gives this result:

```
Pushing Google analytics data. ["_trackEvent", "ABC", "DEF", "X10455", null, true]
```

``` javascript
var self = this,
    event = this.event,
    params = [],
    args = $.each(event, function (key, val) {

        var value;

        if (key === "event") {
            // We don't want to check for the event property in the DOM.
            value = val.value;

        } else {

            // Validate and return the correct value from the DOM.
            value = methods.validate.call(self, val, key);
        }

        params.push(value);
    });

while (params[params.length - 1] === null)
    params.pop();

return params;
```

**Comment by JimBobSquarePants** [comment]
Good idea, I'm wondering whether we would even need to trim the last variable since it is probably going to get handled by Google anyway. What do you think?

**Comment by stiefdirckx** [comment]
You mean skipping the while loop to remove null values at the back of the array? You could leave that out but I always try to minimize the data traffic even how minor it is.

**Comment by JimBobSquarePants** [comment]
Yeah you're right, I'll add the change then.
