### ISSUE TITLE
Events are always triggered twice

### ISSUE THREAD

**Issue by stiefdirckx** [JimBobSquarePants/jQuery-Google-Analytics#5]
I've added this to my page to trigger both click and load events.

```
$('img[data-ga-category]').googleAnalytics({ event: "trackEvent", handler: "load" });
$('a[data-ga-category]').googleAnalytics({ event: "trackEvent", handler: "click" });
```

But now every event is triggered twice for each element. I see something in your code that triggers the tracking 'automagically' with a ':ga' selector. But I can't figure out how to trigger loads en clicks separately. If I leave out my code, everything is triggered as a click.

Could you please provide me with an example of how to do this?

**Comment by JimBobSquarePants** [comment]
Did you unbind the default behaviour? 

e.g.

``` js
// Unbind the default behaviour
$(document).off("ready.ga").on("ready", function () {

    // Run custom code.
    $('img[data-ga-category]').googleAnalytics({ event: "trackEvent", handler: "load" });
    $('a[data-ga-category]').googleAnalytics({ event: "trackEvent", handler: "click" });

}
```

**Comment by stiefdirckx** [comment]
Thanks, I think I didn't do the unbinding properly.

**Comment by JimBobSquarePants** [comment]
No worries.
